### ISSUE TITLE
CT01G: Expand a specific ValueSet (GET)

### ISSUE THREAD

**Issue by lawley** [fhir-crucible/plan_executor#89]
This test and a number of other terminology-specific tests assume that the server is pre-populated with certain FHIR-defined CodeSystems, ValueSets, etc
This is an invalid assumption - the tests should ensure test fixtures like these are created first.

**Comment by jawalonoski** [comment]
Yeah, this is something we struggled with. Most CodeSystems are huge. Even if we use toy CodeSystems and ValueSets for testing we have an issue: just because I POST a ValueSet to your server doesn't require that the terminology operations need to use it.

We could assume that they do, but we could also assume that the FHIR server knows something about FHIR (i.e. FHIR-defined code systems). Either way, we have to make a (bad?) assumption.

I'm open to making this change, however...

**Comment by lawley** [comment]
It may not be perfect, but I think it would be an improvement if the test:
1. Checked for the CodeSystem/ValueSet first with search on url
2. If it doesn't exist, POST it
3. Perform the operation ($expand / $lookup, etc) regardless of outcome of step 2; server may not support search and may be readonly, but may still be populated with "well-known" resources

For tests with really large things (snomed, loinc, etc) at least step 1 could be done, but also might be 
worth separating out those tests as a specific test suites since they have additional code system-specific details in the spec.
