### ISSUE TITLE
The Role FHIR Serve Capability Statement (e.g. fhirVersion) plays in testing and reporting results

### ISSUE THREAD

**Issue by Interopguy** [fhir-crucible/plan_executor#97]
In order to actively and accurately test any HL7 FHIR Implementations - an HL7 FHIR Test Platform would be required to successfully interrogate a FHIR Server Capability Statement - fhirVersion element detail.

Such that if the fhirVersion published is found to be invalid (e.g. FHIR VERSION: 1.5.0) according to FHIR Specifications - Crucible would be able to validate/verify the FHIR Server Version/Implementation conformance or interoperability and report accordingly?

Recommendation: FHIR Server Capability Statement be validated prior to any test platform test execution - to ensure the information available to a FHIR Client would not result in non-interoperable exchange of information.

Further information is available if needed - contact the author of this issue

**Comment by jawalonoski** [comment]
Crucible attempts only to maintain the most active version of DSTU2 and STU3. No other versions are supported or maintained. The live Crucible server receives frequent updates, especially before big version changes and HL7 Connectathon events.

Some servers report strings such as "1.6.0" (valid), "1.5.0" (invalid because no such officially published version of FHIR exists), or "1.6.0-9810" (also invalid because no such officially published version of FHIR exists according to http://hl7.org/fhir/directory.html). Then again, that last one is valid according to common sense.

So, the `fhirVersion` element is not reliable. So, we could either refuse to test someone's server on the basis of fhirVersion, or we could run tests anyway because a user has chosen to initiate a test.

Regardless, we'll make a change that only STU3 servers are tested on the main site, and only DSTU2 servers on the DSTU2 site.

Thanks for the report.

**Comment by jawalonoski** [comment]
We've made the change that only STU3 servers are tested on the main site, and DSTU2 on the alternative site.

**Comment by Interopguy** [comment]
Thanks, but seeking further clarification - according to the FHIR Web Site - fhirVersion 1.4.0, 1.6.0 and 1.8.0 are all published versions of STU3; however, based on FHIR Specifications FHIR Version 1.4.0, 1.6.0 and 1.8.0 each introduce breaking changes (and do not offer backwards compatibility) between them.  So, are you saying/stating the main Crucible site supports STU3 (including all version 1.4.0, 1.6.0 and 1.8.0) or STU3 fhirVersion 1.8.0 only?

**Comment by jawalonoski** [comment]
Crucible only supports the latest version of each STU/DSTU. So, for STU3, we only actively support STU3 v1.8.
